name: build

on:
  push:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build_centos_7:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - name: add operating system packages
      run: yum install -y openssl-devel gcc cmake gcc-c++ freetype-devel expat-devel open-sans-fonts fontconfig-devel
    - name: install rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: add rust to path
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      # v4 results in glibc/abi issues
    - name: checkout code
      uses: actions/checkout@v3
    - name: build
      run: cargo build --release
    - name: strip executable
      run: strip -s target/release/dsar
    - name: install cargo-generate-rpm
      run: cargo install cargo-generate-rpm --version 0.11.0 --force
    - name: generate rpm
      run: cargo generate-rpm --payload-compress=gzip -s 'release = "el.7"'
    - name: executable
      run: ls target/generate-rpm/*
      # settings-actions-general-workflow permissions def: read -> read and write
    - name: release to latest
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: target/generate-rpm/*
      
  build_rocky_8:
    runs-on: ubuntu-latest
    container: rockylinux:8
    steps:
    - name: add operating system packages
      run: yum install -y openssl-devel gcc cmake gcc-c++ freetype-devel expat-devel open-sans-fonts fontconfig-devel
    - name: install rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: add rust to path
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: checkout code
      uses: actions/checkout@v4
    - name: build
      run: cargo build --release
    - name: strip executable
      run: strip -s target/release/dsar
    - name: install cargo-generate-rpm
      run: cargo install cargo-generate-rpm
    - name: generate rpm
      run: cargo generate-rpm -s 'release = "el.8"'
    - name: executable
      run: ls target/generate-rpm/*
      # settings-actions-general-workflow permissions def: read -> read and write
    - name: release to latest
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: target/generate-rpm/*
      
  build_rocky_9:
    runs-on: ubuntu-latest
    container: rockylinux:8
    steps:
    - name: add operating system packages
      run: yum install -y openssl-devel gcc cmake gcc-c++ freetype-devel expat-devel open-sans-fonts fontconfig-devel
    - name: install rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: add rust to path
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: checkout code
      uses: actions/checkout@v4
    - name: build
      run: cargo build --release
    - name: strip executable
      run: strip -s target/release/dsar
    - name: install cargo-generate-rpm
      run: cargo install cargo-generate-rpm
    - name: generate rpm
      run: cargo generate-rpm -s 'release = "el.9"'
    - name: executable
      run: ls target/generate-rpm/*
      # settings-actions-general-workflow permissions def: read -> read and write
    - name: release to latest
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: target/generate-rpm/*
      
