name: build

on:
  push:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  recreate_latest_release:
    runs-on: ubuntu-latest
    steps:
    - name: (re)create latest release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"

  build_intel_rpm:
    if: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - centos:7
          - rockylinux:8
          - rockylinux:9
    container:
      image: ${{ matrix.container }}
    needs: recreate_latest_release
    steps:
   
    - if: ${{ matrix.container == 'centos:7' }}
      uses: actions/checkout@v3
    - if: ${{ matrix.container != 'centos:7' }}
      uses: actions/checkout@v4

    - name: add operating system packages
      run: yum install -y openssl-devel gcc cmake gcc-c++ freetype-devel expat-devel open-sans-fonts fontconfig-devel
    
    - name: install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
     
    - name: cargo build --release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: strip executable
      run: strip -s target/release/dsar

    - if: ${{ matrix.container == 'centos:7' }}
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-generate-rpm --version 0.11.0 --force

    - if: ${{ matrix.container != 'centos:7' }}
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-generate-rpm

    - if: ${{ matrix.container == 'centos:7' }}
      uses: actions-rs/cargo@v1
      with:
        command: generate-rpm
        args: --payload-compress-gzip -s 'release = "el.7"'

    - if: ${{ matrix.container == 'rockylinux:8' }}
      uses: actions-rs/cargo@v1
      with:
        command: generate-rpm
        args: -s 'release = "el.8"'

    - if: ${{ matrix.container == 'rockylinux:9' }}
      uses: actions-rs/cargo@v1
      with:
        command: generate-rpm
        args: -s 'release = "el.9"'

    - name: upload rpm to release
      uses: "AButler/upload-release-assets@v2.0"
      with:
        files: 'target/generate-rpm/*'
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        release-tag: "latest"
      
  build_macos_latest:
    if: true
    runs-on: macos-latest
    needs: recreate_latest_release
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:

    - uses: actions/checkout@v4

    - name: install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: cargo build --release
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=${{ matrix.target }}
   
    - name: obtain current app version
      run: echo "CARGO_APP_VERSION=$(grep ^version Cargo.toml | sed 's/.*"\(.*\)"/\1/')" >> $GITHUB_ENV    

    - name: strip and tar up executable
      run: |
        strip -S target/${{ matrix.target}}/release/dsar
        tar czvf dsar-${{ matrix.target }}-v${{ env.CARGO_APP_VERSION }}-1.tar.gz -C target/${{ matrix.target }}/release dsar

    - name: upload rpm to release
      uses: "AButler/upload-release-assets@v2.0"
      with:
        files: dsar-${{ matrix.target }}-v${{ env.CARGO_APP_VERSION }}-1.tar.gz
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        release-tag: "latest"

